## Cryptocurrency Data Column Definitions

This document explains the columns used in cryptocurrency market data. Each column provides key insights into market position, trading activity, and price trends.

**Market Information**
- **`market_cap`** – The ranking of the cryptocurrency based on its total market value (how much all its coins are worth), following CoinMarketCap’s methodology.
- **`market_cap_strict`** – A stricter calculation of market cap, determined by multiplying the latest trade price by the circulating supply.
- **`market_cap_by_total_supply_strict`** – Market cap calculation based on total supply instead of circulating supply.

**Basic Details**
- **`name`** – The full name of the cryptocurrency (e.g., Bitcoin, Ethereum).
- **`symbol`** – The ticker symbol used to identify the cryptocurrency (e.g., BTC for Bitcoin, ETH for Ethereum).
- **`date_added`** – The date when this cryptocurrency was first listed on the platform.

**Supply and Pricing**
- **`price`** – The latest average trade price of the cryptocurrency across different markets.
- **`circulating_supply`** – The estimated number of coins currently available for trading.
- **`total_supply`** – The total number of coins in existence, excluding any coins that have been permanently burned.
- **`max_supply`** – The maximum number of coins that will ever exist (if this information is available).

**Trading Activity**
- **`num_market_pairs`** – The number of different trading pairs (e.g., BTC/USD, BTC/ETH) available for this cryptocurrency across all exchanges.
- **`volume_24h`** – The total amount of this cryptocurrency traded in the last 24 hours.
- **`volume_7d`** – The total amount traded over the last 7 days.
- **`volume_30d`** – The total amount traded over the last 30 days.

**Price Changes**
- **`percent_change_1h`** – The percentage change in price over the last 1 hour.
- **`percent_change_24h`** – The percentage change in price over the last 24 hours.
- **`percent_change_7d`** – The percentage change in price over the last 7 days.

This dataset helps traders and investors analyze cryptocurrency market trends, liquidity, and performance effectively.

In [ ]:
from dotenv import load_dotenv
import os
from requests import Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
from pprint import pprint

load_dotenv()

API_KEY = os.getenv("COINMARKET_API")

url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
parameters = {
    #'symbol': target_symbol,
    "limit": 20,  # You can adjust the limit to get more or fewer coins
    "convert": "USD",
}

headers = {
    "Accepts": "application/json",
    "X-CMC_PRO_API_KEY": API_KEY,
}

session = Session()
session.headers.update(headers)

# Send a POST request to the server with the data
#response = requests.post(url, json=data_to_send)

try:
    response = session.get(url, params=parameters)
    data = json.loads(response.text)  # Get full JSON response
    pprint(data["data"])  # This prints only the data portion with all coin details
except (ConnectionError, Timeout, TooManyRedirects) as e:
    print(e)

### All keys/columns

In [ ]:
#titles = 
data["data"][0].keys()
#print(titles)

dict_keys(['id', 'name', 'symbol', 'slug', 'num_market_pairs', 'date_added', 'tags', 'max_supply', 'circulating_supply', 'total_supply', 'infinite_supply', 'platform', 'cmc_rank', 'self_reported_circulating_supply', 'self_reported_market_cap', 'tvl_ratio', 'last_updated', 'quote'])

In [ ]:
import pandas as pd

df = pd.DataFrame(data["data"])
df.columns

Index(['id', 'name', 'symbol', 'slug', 'num_market_pairs', 'date_added',
       'tags', 'max_supply', 'circulating_supply', 'total_supply',
       'infinite_supply', 'platform', 'cmc_rank',
       'self_reported_circulating_supply', 'self_reported_market_cap',
       'tvl_ratio', 'last_updated', 'quote'],
      dtype='object')

### All crypto

In [ ]:
crypto = [item['name'] for item in data['data']]
pprint(crypto)

['Bitcoin',
 'Ethereum',
 'Tether USDt',
 'XRP',
 'BNB',
 'Solana',
 'USDC',
 'Dogecoin',
 'Cardano',
 'TRON',
 'Chainlink',
 'Sui',
 'Avalanche',
 'Stellar',
 'Shiba Inu',
 'Toncoin',
 'Litecoin',
 'UNUS SED LEO',
 'Hedera',
 'Hyperliquid']

### Shows all symbols

In [ ]:
crypto = [item['symbol'] for item in data['data']]
pprint(crypto)

['BTC',
 'ETH',
 'USDT',
 'XRP',
 'BNB',
 'SOL',
 'USDC',
 'DOGE',
 'ADA',
 'TRX',
 'LINK',
 'SUI',
 'AVAX',
 'XLM',
 'SHIB',
 'TON',
 'LTC',
 'LEO',
 'HBAR',
 'HYPE']

### Spec a crypto

In [ ]:
target_symbol = "SHIB"
crypto_data = next(item for item in data['data'] if item['symbol'] == target_symbol)
print(json.dumps(crypto_data, indent=0))

{
"id": 5994,
"name": "Shiba Inu",
"symbol": "SHIB",
"slug": "shiba-inu",
"num_market_pairs": 932,
"date_added": "2020-08-01T00:00:00.000Z",
"tags": [
"memes",
"ethereum-ecosystem",
"doggone-doggerel",
"base-ecosystem"
],
"max_supply": null,
"circulating_supply": 589253898077739.6,
"total_supply": 589507260155307.6,
"platform": {
"id": 1027,
"name": "Ethereum",
"symbol": "ETH",
"slug": "ethereum",
"token_address": "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce"
},
"infinite_supply": false,
"cmc_rank": 15,
"self_reported_circulating_supply": null,
"self_reported_market_cap": null,
"tvl_ratio": null,
"last_updated": "2025-02-13T10:03:00.000Z",
"quote": {
"USD": {
"price": 1.6428606738302042e-05,
"volume_24h": 477996439.6294948,
"volume_change_24h": 92.2664,
"percent_change_1h": 0.46678035,
"percent_change_24h": 3.6600328,
"percent_change_7d": 2.10037374,
"percent_change_30d": -23.81737181,
"percent_change_60d": -40.29393325,
"percent_change_90d": -31.81491444,
"market_cap": 9680620560.530699,
"market_cap_dominance": 0.3038,
"fully_diluted_market_cap": 9684782946.47,
"tvl": null,
"last_updated": "2025-02-13T10:03:00.000Z"
}
}
}

### Check All Column Data Types

In [ ]:
df.dtypes

id                                    int64
name                                 object
symbol                               object
slug                                 object
num_market_pairs                      int64
date_added                           object
tags                                 object
max_supply                          float64
circulating_supply                  float64
total_supply                        float64
infinite_supply                        bool
platform                             object
cmc_rank                              int64
self_reported_circulating_supply    float64
self_reported_market_cap            float64
tvl_ratio                           float64
last_updated                         object
quote                                object
dtype: object

In [ ]:
df.head(5)

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote
0,1,Bitcoin,BTC,bitcoin,11938,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.982358e+07,1.982358e+07,False,None,1,NaN,NaN,None,2025-02-13T10:03:00.000Z,"{'USD': {'price': 96262.59642808975, 'volume_2..."
1,1027,Ethereum,ETH,ethereum,9928,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.205454e+08,1.205454e+08,True,None,2,NaN,NaN,None,2025-02-13T10:03:00.000Z,"{'USD': {'price': 2682.1820228477354, 'volume_..."
2,825,Tether USDt,USDT,tether,116496,2015-02-25T00:00:00.000Z,"[stablecoin, asset-backed-stablecoin, ethereum...",NaN,1.419253e+11,1.435668e+11,True,"{'id': 1027, 'name': 'Ethereum', 'symbol': 'ET...",3,NaN,NaN,None,2025-02-13T10:03:00.000Z,"{'USD': {'price': 1.000296585118956, 'volume_2..."
3,52,XRP,XRP,xrp,1528,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, xrp...",1.000000e+11,5.776255e+10,9.998650e+10,False,None,4,NaN,NaN,None,2025-02-13T10:03:00.000Z,"{'USD': {'price': 2.4501940291324162, 'volume_..."
4,1839,BNB,BNB,bnb,2356,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.424790e+08,1.424790e+08,False,None,5,NaN,NaN,None,2025-02-13T10:03:00.000Z,"{'USD': {'price': 706.8332627006363, 'volume_2..."

In [ ]:
df.describe().round(2)

,id,num_market_pairs,max_supply,circulating_supply,total_supply,cmc_rank,self_reported_circulating_supply,self_reported_market_cap
count,20.00,20.00,9.000000e+00,2.000000e+01,2.000000e+01,20.00,2.000000e+00,2.000000e+00
mean,5203.45,8992.10,2.853584e+10,2.949283e+13,2.951028e+13,10.50,1.711819e+09,9.725460e+09
std,8043.58,26031.58,3.499652e+10,1.317541e+14,1.318096e+14,5.92,1.948628e+09,1.693141e+09
min,1.00,51.00,2.100000e+07,1.982358e+07,1.982358e+07,1.00,3.339317e+08,8.528228e+09
25%,746.75,673.00,7.157487e+08,3.924371e+08,5.580129e+08,5.75,1.022876e+09,9.126844e+09
50%,1992.50,1140.50,1.000000e+10,2.791932e+09,7.561098e+09,10.50,1.711819e+09,9.725460e+09
75%,5520.75,2033.50,5.000000e+10,5.649832e+10,6.358282e+10,15.25,2.400763e+09,1.032408e+10
max,32196.00,116496.00,1.000000e+11,5.892539e+14,5.895073e+14,20.00,3.089707e+09,1.092269e+10

In [ ]:
df.describe()[['max_supply']]

         max_supply
count  9.000000e+00
mean   2.853584e+10
std    3.499652e+10
min    2.100000e+07
25%    7.157487e+08
50%    1.000000e+10
75%    5.000000e+10
max    1.000000e+11